
/*
 * Copyright (C) 2026 Antonio Ricciardi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---- DO NOT EDIT BY HAND ----
 * This file is generated by tools/gen_obf.py. Regenerate it instead.
 */

#ifndef C2T_OBFUSCATE_H
#define C2T_OBFUSCATE_H

#include <stddef.h>
#include <stdint.h>

/*
 * Reveals a self-keyed static blob into a caller-provided buffer of at least
 * len + 1 bytes. The keystream is derived from the blob seed via xorshift32,
 * so no fixed ("easy to invert") key is stored anywhere.
 */
static inline void c2t_reveal(uint32_t seed, const unsigned char *src,
                              size_t len, char *dst)
{
    uint32_t state = seed;
    for (size_t i = 0; i < len; ++i) {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        dst[i] = (char)(src[i] ^ (unsigned char)(state & 0xffu));
    }
    dst[len] = '\0';
}

/*
 * Wipes a decoded buffer as soon as its contents are no longer needed.
 * Use with the same buffer that was filled by one of the DEOBF_* helpers.
 */
static inline void c2t_string_wipe(char *dst, size_t len)
{
    if (!dst || len == 0)
        return;
    volatile char *p = dst;
    while (len--) {
        *p++ = 0;
    }
}

// "URL_API_BOT_FORMAT"
static const unsigned char OBF_URL_API_BOT_FORMAT_DATA[33] = {
    0xed, 0xb9, 0x6e, 0x84, 0x6e, 0xf8, 0x95, 0x51, 0xe1, 0xf4, 0xd6, 0xb5, 0xc4, 0xc3, 0xbb, 0xb7, 0xbb, 0x05, 0x39, 0xf6, 0xda, 0x47, 0x47, 0xaa, 0xe3, 0xfa, 0x27, 0x30, 0x0a, 0x88, 0xb7, 0x40, 0xa5
};
#define OBF_URL_API_BOT_FORMAT_LEN 33U
#define DEOBF_URL_API_BOT_FORMAT(buf) c2t_reveal(0x78e7f9caU, OBF_URL_API_BOT_FORMAT_DATA, OBF_URL_API_BOT_FORMAT_LEN, (buf))

// "HOST_TELEGRAM"
static const unsigned char OBF_HOST_TELEGRAM_DATA[16] = {
    0x70, 0x8d, 0x5e, 0xbf, 0x62, 0xe7, 0x73, 0xa3, 0x9f, 0x7e, 0xb0, 0xdd, 0x6c, 0xf7, 0xa4, 0x8d
};
#define OBF_HOST_TELEGRAM_LEN 16U
#define DEOBF_HOST_TELEGRAM(buf) c2t_reveal(0x901d18b4U, OBF_HOST_TELEGRAM_DATA, OBF_HOST_TELEGRAM_LEN, (buf))

// "HEADER_CONTENT_TYPE_FORMAT"
static const unsigned char OBF_HEADER_CONTENT_TYPE_FORMAT_DATA[16] = {
    0x2b, 0x81, 0xb2, 0x9e, 0x55, 0xa5, 0x55, 0x51, 0x8f, 0x77, 0x9e, 0x5e, 0x8f, 0xb8, 0x77, 0x77
};
#define OBF_HEADER_CONTENT_TYPE_FORMAT_LEN 16U
#define DEOBF_HEADER_CONTENT_TYPE_FORMAT(buf) c2t_reveal(0x5246d04fU, OBF_HEADER_CONTENT_TYPE_FORMAT_DATA, OBF_HEADER_CONTENT_TYPE_FORMAT_LEN, (buf))

// "ENDPOINT_SEND_MESSAGE"
static const unsigned char OBF_ENDPOINT_SEND_MESSAGE_DATA[11] = {
    0xc0, 0xc7, 0x3e, 0x42, 0x5d, 0xdb, 0x00, 0x47, 0xe4, 0xa8, 0x0b
};
#define OBF_ENDPOINT_SEND_MESSAGE_LEN 11U
#define DEOBF_ENDPOINT_SEND_MESSAGE(buf) c2t_reveal(0x9a0783eeU, OBF_ENDPOINT_SEND_MESSAGE_DATA, OBF_ENDPOINT_SEND_MESSAGE_LEN, (buf))

// "ENDPOINT_SEND_DOCUMENT"
static const unsigned char OBF_ENDPOINT_SEND_DOCUMENT_DATA[12] = {
    0xda, 0xa9, 0x5e, 0x36, 0xfd, 0x8e, 0xf4, 0xe2, 0x8c, 0xf1, 0x26, 0x98
};
#define OBF_ENDPOINT_SEND_DOCUMENT_LEN 12U
#define DEOBF_ENDPOINT_SEND_DOCUMENT(buf) c2t_reveal(0x4c0dfd5aU, OBF_ENDPOINT_SEND_DOCUMENT_DATA, OBF_ENDPOINT_SEND_DOCUMENT_LEN, (buf))

// "ENDPOINT_SEND_PHOTO"
static const unsigned char OBF_ENDPOINT_SEND_PHOTO_DATA[9] = {
    0x06, 0xe3, 0x4b, 0x2d, 0x82, 0x17, 0x3c, 0x95, 0x1c
};
#define OBF_ENDPOINT_SEND_PHOTO_LEN 9U
#define DEOBF_ENDPOINT_SEND_PHOTO(buf) c2t_reveal(0x090eceb9U, OBF_ENDPOINT_SEND_PHOTO_DATA, OBF_ENDPOINT_SEND_PHOTO_LEN, (buf))

// "ENDPOINT_GET_UPDATES"
static const unsigned char OBF_ENDPOINT_GET_UPDATES_DATA[10] = {
    0x08, 0xcd, 0xf3, 0x93, 0xee, 0x07, 0x8d, 0x7b, 0xf0, 0xd7
};
#define OBF_ENDPOINT_GET_UPDATES_LEN 10U
#define DEOBF_ENDPOINT_GET_UPDATES(buf) c2t_reveal(0x0070f38fU, OBF_ENDPOINT_GET_UPDATES_DATA, OBF_ENDPOINT_GET_UPDATES_LEN, (buf))

// "KEY_BOT_TOKEN"
static const unsigned char OBF_KEY_BOT_TOKEN_DATA[18] = {
    0x5c, 0x23, 0xf8, 0x52, 0xe5, 0xd6, 0xf3, 0x73, 0x2d, 0x50, 0x5e, 0x65, 0x1e, 0x98, 0x0f, 0xb1, 0xa0, 0x0c
};
#define OBF_KEY_BOT_TOKEN_LEN 18U
#define DEOBF_KEY_BOT_TOKEN(buf) c2t_reveal(0x3ae54f82U, OBF_KEY_BOT_TOKEN_DATA, OBF_KEY_BOT_TOKEN_LEN, (buf))

// "KEY_CHAT_ID"
static const unsigned char OBF_KEY_CHAT_ID_DATA[16] = {
    0x5c, 0x82, 0x9c, 0xa0, 0xaa, 0x84, 0x08, 0x5b, 0xe3, 0x48, 0x20, 0xdc, 0xc2, 0xaf, 0x41, 0x77
};
#define OBF_KEY_CHAT_ID_LEN 16U
#define DEOBF_KEY_CHAT_ID(buf) c2t_reveal(0x5d2a27e3U, OBF_KEY_CHAT_ID_DATA, OBF_KEY_CHAT_ID_LEN, (buf))


#endif
