#!/usr/bin/env python3
# Copyright (C) 2026 Antonio Ricciardi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Generator for src/crypto/obfuscate.h

Turns sensitive string constants into self-keyed ciphertext blobs so they do
not appear in plaintext in the compiled binary and cannot be recovered with a
trivial ``strings``/``grep`` pass.

Usage:
    python3 tools/gen_obf.py > src/crypto/obfuscate.h

When adding or changing a string, edit STRINGS below, rerun the script and
commit the regenerated header. The seed for each blob is derived deterministically
from the plaintext, so the output is reproducible and does not need to reveal the
plaintext in a comment.
"""

# (enum_name, plaintext)
# The `enum_name` becomes part of the generated identifiers.
STRINGS = [
    ("URL_API_BOT_FORMAT", "https://api.telegram.org/bot%s/%s"),
    ("HOST_TELEGRAM", "api.telegram.org"),
    ("HEADER_CONTENT_TYPE_FORMAT", "Content-Type: %s"),
    ("ENDPOINT_SEND_MESSAGE", "sendMessage"),
    ("ENDPOINT_SEND_DOCUMENT", "sendDocument"),
    ("ENDPOINT_SEND_PHOTO", "sendPhoto"),
    ("ENDPOINT_GET_UPDATES", "getUpdates"),
    ("KEY_BOT_TOKEN", "TELEGRAM_BOT_TOKEN"),
    ("KEY_CHAT_ID", "TELEGRAM_CHAT_ID"),
]

UINT32_MASK = 0xFFFFFFFF


def fnv1a32(data: bytes) -> int:
    """FNV-1a 32-bit; never returns 0 for a non-trivial input."""
    hashval = 0x811C9DC5
    for byte in data:
        hashval ^= byte
        hashval = (hashval * 0x01000193) & UINT32_MASK
    # Guarantee a non-zero stream seed for xorshift.
    if hashval == 0:
        hashval = 0x9E3779B9
    return hashval & UINT32_MASK


def keystream_bytes(seed: int, count: int) -> bytes:
    """xorshift32 keystream matching c2t_reveal() in obfuscate.h."""
    state = seed & UINT32_MASK
    if state == 0:
        state = 0x9E3779B9
    out = bytearray()
    for _ in range(count):
        state ^= (state << 13) & UINT32_MASK
        state ^= state >> 17
        state ^= (state << 5) & UINT32_MASK
        out.append(state & 0xFF)
    return bytes(out)


def obfuscate(plaintext: str) -> tuple[int, bytes]:
    data = plaintext.encode("utf-8")
    seed = fnv1a32(data)
    stream = keystream_bytes(seed, len(data))
    cipher = bytes(b ^ s for b, s in zip(data, stream))
    return seed, cipher


def format_array(name: str, data: bytes) -> str:
    values = ", ".join("0x%02x" % b for b in data)
    return (
        f"static const unsigned char {name}[{len(data)}] = {{\n"
        f"    {values}\n"
        f"}};"
    )


def main() -> None:
    header = []
    header.append("""
/*
 * Copyright (C) 2026 Antonio Ricciardi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---- DO NOT EDIT BY HAND ----
 * This file is generated by tools/gen_obf.py. Regenerate it instead.
 */

#ifndef C2T_OBFUSCATE_H
#define C2T_OBFUSCATE_H

#include <stddef.h>
#include <stdint.h>

/*
 * Reveals a self-keyed static blob into a caller-provided buffer of at least
 * len + 1 bytes. The keystream is derived from the blob seed via xorshift32,
 * so no fixed ("easy to invert") key is stored anywhere.
 */
static inline void c2t_reveal(uint32_t seed, const unsigned char *src,
                              size_t len, char *dst)
{
    uint32_t state = seed;
    for (size_t i = 0; i < len; ++i) {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        dst[i] = (char)(src[i] ^ (unsigned char)(state & 0xffu));
    }
    dst[len] = '\\0';
}

/*
 * Wipes a decoded buffer as soon as its contents are no longer needed.
 * Use with the same buffer that was filled by one of the DEOBF_* helpers.
 */
static inline void c2t_string_wipe(char *dst, size_t len)
{
    if (!dst || len == 0)
        return;
    volatile char *p = dst;
    while (len--) {
        *p++ = 0;
    }
}
""".rstrip())

    for name, plaintext in STRINGS:
        seed, cipher = obfuscate(plaintext)
        blobs = [f"// \"{name}\""]
        blobs.append(format_array(f"OBF_{name}_DATA", cipher))
        blobs.append(f"#define OBF_{name}_LEN {len(cipher)}U")
        blobs.append(f"#define DEOBF_{name}(buf) c2t_reveal(0x{seed:08x}U, OBF_{name}_DATA, OBF_{name}_LEN, (buf))")
        header.append("\n".join(blobs))

    header.append("\n#endif")
    print("\n\n".join(header))


if __name__ == "__main__":
    main()
